// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzSzpsjWEgXhpn1nqfaPL6j9ieALd-SM',
    appId: '1:674973218419:web:9c7d9629675f69d1c95c06',
    messagingSenderId: '674973218419',
    projectId: 'myquizgame-82c5c',
    authDomain: 'myquizgame-82c5c.firebaseapp.com',
    storageBucket: 'myquizgame-82c5c.firebasestorage.app',
    databaseURL: 'https://myquizgame-82c5c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAzSzpsjWEgXhpn1nqfaPL6j9ieALd-SM',
    appId: '1:674973218419:android:9c7d9629675f69d1c95c06',
    messagingSenderId: '674973218419',
    projectId: 'myquizgame-82c5c',
    storageBucket: 'myquizgame-82c5c.firebasestorage.app',
    databaseURL: 'https://myquizgame-82c5c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAzSzpsjWEgXhpn1nqfaPL6j9ieALd-SM',
    appId: '1:674973218419:ios:9c7d9629675f69d1c95c06',
    messagingSenderId: '674973218419',
    projectId: 'myquizgame-82c5c',
    storageBucket: 'myquizgame-82c5c.firebasestorage.app',
    iosBundleId: 'com.example.project1',
    databaseURL: 'https://myquizgame-82c5c-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAzSzpsjWEgXhpn1nqfaPL6j9ieALd-SM',
    appId: '1:674973218419:ios:9c7d9629675f69d1c95c06',
    messagingSenderId: '674973218419',
    projectId: 'myquizgame-82c5c',
    storageBucket: 'myquizgame-82c5c.firebasestorage.app',
    iosBundleId: 'com.example.project1',
    databaseURL: 'https://myquizgame-82c5c-default-rtdb.europe-west1.firebasedatabase.app',
  );
} 